apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecev.fullname" . }}-config
  labels:
    {{- include "ecev.labels" . | nindent 4 }}
data:
  config.json: |
    {{- .Files.Get "files/config.json" | nindent 4 }}
  catalog.json: |
    {{- .Files.Get "files/catalog.json" | nindent 4 }}
