{{- if .Values.auth.username }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecev.fullname" . }}-auth
  labels:
    {{- include "ecev.labels" . | nindent 4 }}
type: Opaque
stringData:
  BSSF_USERNAME: {{ .Values.auth.username | quote }}
  BSSF_PASSWORD: {{ .Values.auth.password | quote }}
  BSSF_CLIENT_ID: {{ .Values.auth.clientId | quote }}
  BSSF_TOKEN_ENDPOINT: {{ .Values.auth.tokenEndpoint | quote }}
{{- end }}
